##### NMAsurv #####

options(encoding = "UTF-8")
suppressWarnings(suppressMessages(library(broom)))
suppressWarnings(suppressMessages(library(clipr)))
suppressWarnings(suppressMessages(library(discSurv)))
suppressWarnings(suppressMessages(library(doBy)))
suppressWarnings(suppressMessages(library(dplyr)))
suppressWarnings(suppressMessages(library(DT)))
suppressWarnings(suppressMessages(library(flexsurv)))
suppressWarnings(suppressMessages(library(flextable)))
suppressWarnings(suppressMessages(library(ggmcmc)))
suppressWarnings(suppressMessages(library(ggplot2)))
suppressWarnings(suppressMessages(library(grid)))
suppressWarnings(suppressMessages(library(gridExtra)))
suppressWarnings(suppressMessages(library(heemod)))
suppressWarnings(suppressMessages(library(knitr)))
suppressWarnings(suppressMessages(library(lme4)))
suppressWarnings(suppressMessages(library(magrittr)))
suppressWarnings(suppressMessages(library(markdown)))
suppressWarnings(suppressMessages(library(markdownInput)))
suppressWarnings(suppressMessages(library(MatrixModels)))
suppressWarnings(suppressMessages(library(metafor)))
suppressWarnings(suppressMessages(library(netmeta)))
suppressWarnings(suppressMessages(library(officer)))
suppressWarnings(suppressMessages(library(R.utils)))
suppressWarnings(suppressMessages(library(R2jags)))
suppressWarnings(suppressMessages(library(rclipboard)))
suppressWarnings(suppressMessages(library(readxl)))
suppressWarnings(suppressMessages(library(rhandsontable)))
suppressWarnings(suppressMessages(library(rmarkdown)))
suppressWarnings(suppressMessages(library(scales)))
suppressWarnings(suppressMessages(library(shiny)))
suppressWarnings(suppressMessages(library(shinyalert)))
suppressWarnings(suppressMessages(library(shinyBS)))
suppressWarnings(suppressMessages(library(shinycssloaders)))
suppressWarnings(suppressMessages(library(shinydashboard)))
suppressWarnings(suppressMessages(library(shinydashboard)))
suppressWarnings(suppressMessages(library(shinydashboardPlus)))
suppressWarnings(suppressMessages(library(shinyhelper)))
suppressWarnings(suppressMessages(library(shinyjs)))
suppressWarnings(suppressMessages(library(shinymanager)))
suppressWarnings(suppressMessages(library(shinytitle)))
suppressWarnings(suppressMessages(library(shinyWidgets)))
suppressWarnings(suppressMessages(library(slickR)))
suppressWarnings(suppressMessages(library(survHE)))
suppressWarnings(suppressMessages(library(survival)))
suppressWarnings(suppressMessages(library(survminer)))
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(writexl)))

R.utils::sourceDirectory(path = "R", modifiedOnly = FALSE)

options(shiny.sanitize.errors = FALSE)

